services:
  moodleserver:
    build:
      context: .
      dockerfile: ./dockerfiles/apache/Dockerfile
    restart: unless-stopped
    environment:
      - MOODLE_URL=${MOODLE_URL}
      - MOODLE_ADMIN=${ADMIN_USERNAME}
      - MOODLE_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - MOODLE_ADMIN_EMAIL=${ADMIN_EMAIL}
      - MOODLE_DB_TYPE=mariadb
      - MOODLE_DB_HOST=database
      - MOODLE_DB_NAME=moodle
      - MOODLE_DB_USER=${DB_USER}
      - MOODLE_DB_PASSWORD=${DB_PASSWORD}
      - MOODLE_DB_PSD=${DB_PASSWORD}
      - MOODLE_DB_PORT=3306
      - MOODLE_REVERSE_LB=${MOODLE_REVERSE_LB}
      - MOODLE_SSL=${MOODLE_SSL}
      - MOODLE_EMAIL_TYPE_QMAIL=${MOODLE_EMAIL_TYPE_QMAIL}
      - MOODLE_EMAIL_HOST=${MOODLE_EMAIL_HOST}
    volumes:
      - moodleserver_moodle_data:/var/www/html
      - moodleserver_moodledata:/var/moodledata
    depends_on:
      - database
      - moodleredis
      - memcached
    networks:
      - moodleserver-network
      - dokploy-network

  moodleredis:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - moodleredis_data:/data
    networks:
      - moodleserver-network

  memcached:
    image: memcached:1.6-alpine
    command: memcached
    networks:
      - moodleserver-network

  database:
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=moodle
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - database_mariadb_data:/var/lib/mysql
    networks:
      - moodleserver-network

volumes:
  database_mariadb_data:
  moodleserver_moodle_data:
  moodleserver_moodledata:
  moodleredis_data:
networks:
  moodleserver-network:
    driver: bridge
  dokploy-network:
    external: true

